version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tapyfood_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "24-08-2004KAT"
      MYSQL_DATABASE: "tapyfood_db"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./tapyfood.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: tapyfood_web
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: "24-08-2004KAT"

volumes:
  db_data:
